services:
  renderer:
    build:
      context: ./renderer
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "8080:80"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      BACKEND_HOST: 0.0.0.0
      BACKEND_PORT: "8080"
