import type { ConfiguratorExerciseVariant, ExerciseSummary, TrainingPlanDefinitionRequest, TrainingPlanDetailResponse, TrainingPlanGuidance, TrainingPlanGuidanceValues } from "./workout-contract";
import { TextInputBinding } from "./text-input-binding";

export const pbConfiguratorTrainingPlanEditorScreenTag = "pb-configurator-training-plan-editor-screen";
type ExerciseOption = ExerciseSummary & { variants: ConfiguratorExerciseVariant[] };
export type ConfiguratorTrainingPlanEditorScreenState = { trainingPlanId: string; detail: TrainingPlanDetailResponse | null; exercises: ExerciseOption[]; isLoading: boolean; errorMessage: string | null };
type DraftExercise = { exerciseId: string; variantIds: string[]; position: number; original: boolean };
type GuidanceDraft = { defaults: TrainingPlanGuidanceValues; overrides: Record<string, TrainingPlanGuidanceValues> };
type GuidanceOverlay = { exerciseId: string; variantId: string | null; targetSets: string; repMin: string; repMax: string; error: string | null };
type SaveResult = { ok: boolean; errorMessage?: string; createsNewVersion?: boolean };
const esc = (v: string) => v.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#39;");
const norm = (v: string) => v.trim().toLocaleLowerCase("en-US");

class PbConfiguratorTrainingPlanEditorScreenElement extends HTMLElement {
  #state: ConfiguratorTrainingPlanEditorScreenState = { trainingPlanId: "", detail: null, exercises: [], isLoading: false, errorMessage: null };
  #loaded = ""; #name = ""; #draft: DraftExercise[] = []; #guidance: Record<string, GuidanceDraft> = {}; #guidanceDirty = false; #guidanceOverlay: GuidanceOverlay | null = null; #reordering = false; #dragging: { exerciseId: string; pointerId: number } | null = null; #insertionExerciseId: string | null = null; #insertionAfterExerciseId: string | null = null; #exercisePickerOpen = false; #exerciseQuery = ""; #variantPickerExerciseId: string | null = null; #variantPickerQuery = ""; #error: string | null = null; #saving = false; #assessingSave = false; #saveConfirmation: string | null = null; #pendingSave: TrainingPlanDefinitionRequest | null = null;
  #textInput = new TextInputBinding(this, ({ field, value }) => this.#onTextInput(field, value));
  connectedCallback(): void { this.#render(); this.addEventListener("click", this.#onClick); this.addEventListener("keydown", this.#onKeyDown); this.addEventListener("pointerdown", this.#onPointerDown); document.addEventListener("pointermove", this.#onPointerMove); document.addEventListener("pointerup", this.#onPointerUp); document.addEventListener("pointercancel", this.#onPointerUp); this.#textInput.connect(); }
  disconnectedCallback(): void { this.removeEventListener("click", this.#onClick); this.removeEventListener("keydown", this.#onKeyDown); this.removeEventListener("pointerdown", this.#onPointerDown); document.removeEventListener("pointermove", this.#onPointerMove); document.removeEventListener("pointerup", this.#onPointerUp); document.removeEventListener("pointercancel", this.#onPointerUp); this.#textInput.disconnect(); }
  set state(value: ConfiguratorTrainingPlanEditorScreenState) { this.#state = value; const key = value.detail ? `${value.trainingPlanId}:${value.detail.selected_version_number}` : ""; if (key && key !== this.#loaded) { this.#loaded = key; this.#name = value.detail!.name; this.#draft = value.detail!.exercises.map((item) => ({ exerciseId: this.#exerciseFor(item.variants[0]?.variant_id ?? ""), variantIds: item.variants.map((variant) => variant.variant_id), position: item.exercise_position, original: true })).filter((item) => item.exerciseId); this.#guidance = Object.fromEntries(value.detail!.exercises.map((item) => [this.#exerciseFor(item.variants[0]?.variant_id ?? ""), { defaults: { ...item.default_guidance }, overrides: Object.fromEntries(item.variants.filter((variant) => variant.guidance_override).map((variant) => [variant.variant_id, { ...variant.guidance_override! }])) }]).filter(([exerciseId]) => exerciseId)); this.#guidanceDirty = false; this.#guidanceOverlay = null; this.#reordering = false; this.#dragging = null; this.#insertionExerciseId = null; this.#insertionAfterExerciseId = null; this.#exercisePickerOpen = false; this.#exerciseQuery = ""; this.#variantPickerExerciseId = null; this.#variantPickerQuery = ""; this.#error = null; this.#saving = false; this.#saveConfirmation = null; this.#pendingSave = null; } this.#render(); }
  get state(): ConfiguratorTrainingPlanEditorScreenState { return this.#state; }
  #exerciseFor(variantId: string): string { return this.#state.exercises.find((exercise) => exercise.variants.some((variant) => variant.id === variantId))?.id ?? ""; }
  #exercise(id: string) { return this.#state.exercises.find((item) => item.id === id) ?? null; }
  #emptyGuidance(): TrainingPlanGuidanceValues { return { target_sets: null, rep_min: null, rep_max: null }; }
  #guidanceFor(exerciseId: string): GuidanceDraft { return this.#guidance[exerciseId] ?? { defaults: this.#emptyGuidance(), overrides: {} }; }
  #effectiveGuidance(exerciseId: string, variantId: string): TrainingPlanGuidanceValues { const guidance = this.#guidanceFor(exerciseId); return guidance.overrides[variantId] ?? guidance.defaults; }
  #existingOverrideCount(): number { return this.#state.detail?.exercises.reduce((count, exercise) => count + exercise.variants.filter((variant) => variant.guidance_override !== null).length, 0) ?? 0; }
  #guidanceRequest(): TrainingPlanGuidance { return { exercises: this.#draft.map((draft) => { const guidance = this.#guidanceFor(draft.exerciseId); return { exercise_id: draft.exerciseId, defaults: { ...guidance.defaults }, variant_overrides: draft.variantIds.flatMap((variantId) => guidance.overrides[variantId] ? [{ variant_id: variantId, guidance: { ...guidance.overrides[variantId] } }] : []) }; }) }; }
  #openGuidanceOverlay(exerciseId: string, variantId: string | null): void { const values = variantId ? this.#effectiveGuidance(exerciseId, variantId) : this.#guidanceFor(exerciseId).defaults; this.#guidanceOverlay = { exerciseId, variantId, targetSets: values.target_sets?.toString() ?? "", repMin: values.rep_min?.toString() ?? "", repMax: values.rep_max?.toString() ?? "", error: null }; this.#render(); }
  #guidanceOverlayValues(overlay: GuidanceOverlay): TrainingPlanGuidanceValues | null { const parse = (value: string, label: string): number | null | "invalid" => { if (!value.trim()) return null; const parsed = Number(value); return Number.isInteger(parsed) && parsed > 0 ? parsed : "invalid"; }; const targetSets = parse(overlay.targetSets, "Target sets"), repMin = parse(overlay.repMin, "Minimum repetitions"), repMax = parse(overlay.repMax, "Maximum repetitions"); if (targetSets === "invalid" || repMin === "invalid" || repMax === "invalid") { overlay.error = "Guidance values must be positive whole numbers."; return null; } if ((repMin === null) !== (repMax === null)) { overlay.error = "Enter both repetition bounds, or leave both blank."; return null; } if (repMin !== null && repMax !== null && repMin > repMax) { overlay.error = "Minimum repetitions cannot exceed maximum repetitions."; return null; } return { target_sets: targetSets, rep_min: repMin, rep_max: repMax }; }
  #saveGuidanceOverlay(): void { const overlay = this.#guidanceOverlay; if (!overlay) return; const values = this.#guidanceOverlayValues(overlay); if (!values) { this.#render(); return; } const current = this.#guidanceFor(overlay.exerciseId); const overrides = { ...current.overrides }; if (overlay.variantId) overrides[overlay.variantId] = values; this.#guidance = { ...this.#guidance, [overlay.exerciseId]: { defaults: overlay.variantId ? current.defaults : values, overrides } }; this.#guidanceDirty = true; this.#guidanceOverlay = null; this.#render(); }
  #clearVariantGuidance(): void { const overlay = this.#guidanceOverlay; if (!overlay?.variantId) return; const current = this.#guidanceFor(overlay.exerciseId); const overrides = { ...current.overrides }; delete overrides[overlay.variantId]; this.#guidance = { ...this.#guidance, [overlay.exerciseId]: { ...current, overrides } }; this.#guidanceDirty = true; this.#guidanceOverlay = null; this.#render(); }
  #emit(action: string, payload?: Record<string, unknown>, respond?: (result: SaveResult) => void) { this.dispatchEvent(new CustomEvent("pb-ui-action", { bubbles: true, composed: true, detail: { action, ...(payload ? { payload } : {}), ...(respond ? { respond } : {}) } })); }
  #assessSave(request: TrainingPlanDefinitionRequest): void { this.#assessingSave = true; this.#render(); this.#emit("assess-configurator-training-plan-save", { trainingPlanId: this.#state.trainingPlanId, request }, (result) => { this.#assessingSave = false; if (!result.ok) { this.#error = result.errorMessage ?? "Unable to assess training plan changes right now."; this.#render(); return; } const renamed = this.#state.detail!.name !== request.name; const existingOverrides = this.#existingOverrideCount(); if (renamed || result.createsNewVersion || (this.#guidanceDirty && existingOverrides > 0)) { this.#pendingSave = this.#guidanceDirty && existingOverrides > 0 ? { ...request, replace_existing_variant_override_count: existingOverrides } : request; this.#saveConfirmation = [renamed ? "Renaming a Training Plan can affect how historical workouts are understood." : "", result.createsNewVersion ? "Structural changes will create a new Training Plan Version. Previous versions remain unchanged." : "", this.#guidanceDirty && existingOverrides > 0 ? `This will replace ${existingOverrides} existing variant exception${existingOverrides === 1 ? "" : "s"}.` : ""].filter(Boolean).join(" "); this.#render(); } else this.#save(request); }); }
  #save(request: TrainingPlanDefinitionRequest): void { this.#saving = true; this.#render(); this.#emit("save-configurator-training-plan", { trainingPlanId: this.#state.trainingPlanId, request }, (result) => { this.#saving = false; this.#error = result.ok ? null : result.errorMessage ?? "Unable to save training plan right now."; this.#render(); }); }
  #onTextInput(field: string, value: string): void { if (field === "plan-name") this.#name = value; else if (field === "exercise-search") this.#exerciseQuery = value; else if (field === "variant-picker-search") this.#variantPickerQuery = value; else if (field.startsWith("guidance-") && this.#guidanceOverlay) { const name = field.slice("guidance-".length) as "targetSets" | "repMin" | "repMax"; this.#guidanceOverlay[name] = value; this.#guidanceOverlay.error = null; } else return; this.#error = null; this.#render(); }
  #onKeyDown = (event: KeyboardEvent) => { if (event.key !== "Escape") return; if (this.#guidanceOverlay) { event.preventDefault(); this.#guidanceOverlay = null; this.#render(); return; } if (this.#variantPickerExerciseId) { event.preventDefault(); this.#variantPickerExerciseId = null; this.#variantPickerQuery = ""; this.#render(); return; } if (this.#exercisePickerOpen) { event.preventDefault(); this.#exercisePickerOpen = false; this.#exerciseQuery = ""; this.#render(); } };
  #onPointerDown = (event: PointerEvent) => { const target = event.target; if (!this.#reordering || !(target instanceof Element)) return; const handle = target.closest<HTMLElement>("[data-reorder-handle]"); const exerciseId = handle?.dataset.exerciseId ?? ""; if (!handle || !this.contains(handle) || !this.#draft.some((item) => item.exerciseId === exerciseId)) return; event.preventDefault(); this.#dragging = { exerciseId, pointerId: event.pointerId }; this.#insertionExerciseId = exerciseId; this.#insertionAfterExerciseId = null; };
  #onPointerMove = (event: PointerEvent) => { const dragging = this.#dragging; if (!dragging || event.pointerId !== dragging.pointerId) return; const list = this.querySelector<HTMLElement>(".configurator-training-plan-reorder-list"); const rows = [...this.querySelectorAll<HTMLElement>(".configurator-training-plan-reorder-row")]; if (!list || rows.length === 0) return; const bounds = list.getBoundingClientRect(); if (event.clientY < bounds.top + 48) list.scrollBy?.({ top: -24 }); else if (event.clientY > bounds.bottom - 48) list.scrollBy?.({ top: 24 }); const target = rows.find((row) => event.clientY < row.getBoundingClientRect().top + row.getBoundingClientRect().height / 2); const targetId = target?.dataset.exerciseId ?? ""; const from = this.#draft.findIndex((item) => item.exerciseId === dragging.exerciseId); const to = target ? this.#draft.findIndex((item) => item.exerciseId === targetId) : this.#draft.length; if (from < 0 || to < 0) return; this.#insertionExerciseId = targetId || null; this.#insertionAfterExerciseId = target ? null : rows.at(-1)?.dataset.exerciseId ?? null; if (from !== to) { const next = [...this.#draft]; const [moved] = next.splice(from, 1); next.splice(target && from < to ? to - 1 : to, 0, moved); this.#draft = next.map((item, index) => ({ ...item, position: index + 1 })); } this.#render(); };
  #onPointerUp = (event: PointerEvent) => { if (!this.#dragging || event.pointerId !== this.#dragging.pointerId) return; this.#dragging = null; this.#insertionExerciseId = null; this.#insertionAfterExerciseId = null; this.#render(); };
  #onClick = (event: Event) => { const target = event.target; if (!(target instanceof Element)) return; const button = target.closest<HTMLElement>("[data-ui-action]"); if (!button || !this.contains(button)) return; const action = button.dataset.uiAction;
    if (action === "navigate-back-from-configurator-training-plan-detail") return this.#emit(action);
    if (action === "start-plan-exercise-reorder") { this.#reordering = true; this.#render(); return; }
    if (action === "finish-plan-exercise-reorder") { this.#reordering = false; this.#dragging = null; this.#insertionExerciseId = null; this.#insertionAfterExerciseId = null; this.#render(); return; }
    if (action === "open-plan-exercise-picker") { this.#exercisePickerOpen = true; this.#exerciseQuery = ""; this.#render(); return; }
    if (action === "dismiss-plan-exercise-picker") { this.#exercisePickerOpen = false; this.#exerciseQuery = ""; this.#render(); return; }
    if (action === "open-plan-variant-picker") { const exerciseId = button.dataset.exerciseId ?? ""; if (this.#exercise(exerciseId)) { this.#variantPickerExerciseId = exerciseId; this.#variantPickerQuery = ""; this.#render(); } return; }
    if (action === "dismiss-plan-variant-picker") { this.#variantPickerExerciseId = null; this.#variantPickerQuery = ""; this.#render(); return; }
    if (action === "add-plan-exercise") { const id = button.dataset.exerciseId ?? ""; if (this.#exercise(id) && !this.#draft.some((item) => item.exerciseId === id)) { this.#draft.push({ exerciseId: id, variantIds: [], position: this.#draft.length + 1, original: false }); this.#exercisePickerOpen = false; this.#exerciseQuery = ""; this.#render(); } return; }
    if (action === "remove-plan-exercise") { const id = button.dataset.exerciseId ?? ""; this.#draft = this.#draft.filter((item) => item.exerciseId !== id); this.#render(); return; }
    if (action === "add-plan-variant") { const exerciseId = button.dataset.exerciseId ?? "", variantId = button.dataset.variantId ?? ""; const item = this.#draft.find((candidate) => candidate.exerciseId === exerciseId); if (item && this.#exercise(exerciseId)?.variants.some((variant) => variant.id === variantId) && !item.variantIds.includes(variantId)) { item.variantIds.push(variantId); this.#variantPickerExerciseId = null; this.#variantPickerQuery = ""; this.#render(); } return; }
    if (action === "remove-plan-variant") { const exerciseId = button.dataset.exerciseId ?? "", variantId = button.dataset.variantId ?? ""; const item = this.#draft.find((candidate) => candidate.exerciseId === exerciseId); if (item && item.variantIds.length > 1) { item.variantIds = item.variantIds.filter((id) => id !== variantId); this.#render(); } return; }
    if (action === "open-exercise-guidance") { const exerciseId = button.dataset.exerciseId ?? ""; if (this.#exercise(exerciseId)) this.#openGuidanceOverlay(exerciseId, null); return; }
    if (action === "open-variant-guidance") { const exerciseId = button.dataset.exerciseId ?? "", variantId = button.dataset.variantId ?? ""; if (this.#exercise(exerciseId) && variantId) this.#openGuidanceOverlay(exerciseId, variantId); return; }
    if (action === "dismiss-guidance-overlay") { this.#guidanceOverlay = null; this.#render(); return; }
    if (action === "save-guidance-overlay") { this.#saveGuidanceOverlay(); return; }
    if (action === "clear-variant-guidance") { this.#clearVariantGuidance(); return; }
    if (action === "dismiss-training-plan-save-confirmation") { this.#saveConfirmation = null; this.#pendingSave = null; this.#render(); return; }
    if (action === "confirm-training-plan-save") { const request = this.#pendingSave; this.#saveConfirmation = null; this.#pendingSave = null; if (request) this.#save(request); else this.#render(); return; }
    if (action !== "save-configurator-training-plan" || this.#saving || this.#assessingSave) return;
    if (!this.#name.trim() || this.#draft.length === 0 || this.#draft.some((item) => item.variantIds.length === 0)) { this.#error = !this.#name.trim() ? "Plan name is required." : this.#draft.length === 0 ? "Add at least one Exercise." : "Choose at least one Variant for every Exercise."; this.#render(); return; }
    const request: TrainingPlanDefinitionRequest = { name: this.#name, exercises: this.#draft.map((item) => ({ exercise_id: item.exerciseId, allowed_variant_ids: item.variantIds })), ...(this.#guidanceDirty ? { guidance: this.#guidanceRequest() } : {}) };
    this.#assessSave(request);
  };
  #guidanceSummary(variant: TrainingPlanGuidanceValues): string { const sets = variant.target_sets === null ? "Sets not set" : `${variant.target_sets} sets`; const reps = variant.rep_min === null || variant.rep_max === null ? "reps not set" : variant.rep_min === variant.rep_max ? `${variant.rep_min} reps` : `${variant.rep_min}–${variant.rep_max} reps`; return `${sets} · ${reps}`; }
  #renderGuidanceOverlay(): string { const overlay = this.#guidanceOverlay; if (!overlay) return ""; const exercise = this.#exercise(overlay.exerciseId); const variant = overlay.variantId ? exercise?.variants.find((item) => item.id === overlay.variantId) : null; const inherited = overlay.variantId ? this.#guidanceSummary(this.#guidanceFor(overlay.exerciseId).defaults) : ""; const isException = overlay.variantId !== null; return `<div class="secs-picker-layer" role="presentation"><button type="button" class="secs-picker-backdrop" data-ui-action="dismiss-guidance-overlay" aria-label="Close guidance editor"></button><section class="secs-picker-sheet configurator-load-profile-picker configurator-guidance-overlay" role="dialog" aria-modal="true" aria-labelledby="configurator-guidance-title"><header class="configurator-load-profile-picker-header"><h2 id="configurator-guidance-title" class="secs-picker-title">${isException ? `Guidance exception · ${esc(variant?.name ?? "Variant")}` : `Exercise guidance · ${esc(exercise?.name ?? "Exercise")}`}</h2>${isException ? `<p class="start-copy">Inherits: ${esc(inherited)}. Saving creates a variant-only exception.</p>` : '<p class="start-copy">Optional defaults for this Exercise and its variants.</p>'}</header><div class="configurator-guidance-fields"><label class="configurator-gym-field"><span class="configurator-gym-field-label">Target sets</span><input class="configurator-gym-input" type="number" min="1" inputmode="numeric" data-field="guidance-targetSets" value="${esc(overlay.targetSets)}" aria-label="Target sets" /></label><label class="configurator-gym-field"><span class="configurator-gym-field-label">Minimum repetitions</span><input class="configurator-gym-input" type="number" min="1" inputmode="numeric" data-field="guidance-repMin" value="${esc(overlay.repMin)}" aria-label="Minimum repetitions" /></label><label class="configurator-gym-field"><span class="configurator-gym-field-label">Maximum repetitions</span><input class="configurator-gym-input" type="number" min="1" inputmode="numeric" data-field="guidance-repMax" value="${esc(overlay.repMax)}" aria-label="Maximum repetitions" /></label></div>${overlay.error ? `<p class="start-error" role="alert">${esc(overlay.error)}</p>` : ""}<div class="confirm-dialog-actions">${isException ? '<button type="button" class="nav-button nav-button-secondary" data-ui-action="clear-variant-guidance">Use inherited guidance</button>' : ""}<button type="button" class="nav-button nav-button-secondary" data-ui-action="dismiss-guidance-overlay">Cancel</button><button type="button" class="nav-button" data-ui-action="save-guidance-overlay">Save guidance</button></div></section></div>`; }
  #renderExercisePicker(available: ExerciseOption[]): string { if (!this.#exercisePickerOpen) return ""; return `<div class="secs-picker-layer" role="presentation"><button type="button" class="secs-picker-backdrop" data-ui-action="dismiss-plan-exercise-picker" aria-label="Close Exercise picker"></button><section class="secs-picker-sheet configurator-load-profile-picker" role="dialog" aria-modal="true" aria-labelledby="configurator-plan-exercise-picker-title"><header class="configurator-load-profile-picker-header"><h2 id="configurator-plan-exercise-picker-title" class="secs-picker-title">Add Exercise</h2><input class="configurator-gym-input" type="search" data-field="exercise-search" value="${esc(this.#exerciseQuery)}" placeholder="Search Exercises" aria-label="Search Exercises" autocomplete="off" /></header><div class="configurator-load-profile-picker-options" role="listbox" aria-label="Available Exercises">${available.length === 0 ? '<p class="start-copy">No Exercises available to add.</p>' : available.map((exercise) => `<button type="button" class="configurator-load-profile-picker-option" data-ui-action="add-plan-exercise" data-exercise-id="${esc(exercise.id)}" role="option"><span>${esc(exercise.name)}</span></button>`).join("")}</div></section></div>`; }
  #renderVariantPicker(): string { const exerciseId = this.#variantPickerExerciseId; const draft = exerciseId ? this.#draft.find((item) => item.exerciseId === exerciseId) : null; const exercise = exerciseId ? this.#exercise(exerciseId) : null; if (!draft || !exercise) return ""; const choices = exercise.variants.filter((variant) => !draft.variantIds.includes(variant.id) && (!this.#variantPickerQuery || norm(variant.name).includes(norm(this.#variantPickerQuery)))); return `<div class="secs-picker-layer" role="presentation"><button type="button" class="secs-picker-backdrop" data-ui-action="dismiss-plan-variant-picker" aria-label="Close Variant picker"></button><section class="secs-picker-sheet configurator-load-profile-picker" role="dialog" aria-modal="true" aria-labelledby="configurator-plan-variant-picker-title"><header class="configurator-load-profile-picker-header"><h2 id="configurator-plan-variant-picker-title" class="secs-picker-title">Add Variant</h2><input class="configurator-gym-input" type="search" data-field="variant-picker-search" value="${esc(this.#variantPickerQuery)}" placeholder="Search Variants" aria-label="Search Variants" autocomplete="off" /></header><div class="configurator-load-profile-picker-options" role="listbox" aria-label="Available Variants">${choices.length === 0 ? '<p class="start-copy">No Variants available to add.</p>' : choices.map((variant) => `<button type="button" class="configurator-load-profile-picker-option" data-ui-action="add-plan-variant" data-exercise-id="${esc(exercise.id)}" data-variant-id="${esc(variant.id)}" role="option"><span>${esc(variant.name)}</span></button>`).join("")}</div></section></div>`; }
  #render(): void { const detail = this.#state.detail; if (this.#state.isLoading) { this.innerHTML = '<p class="start-status">Loading training plan...</p>'; return; } if (this.#state.errorMessage || !detail) { this.innerHTML = `<p class="start-error" role="alert">${esc(this.#state.errorMessage ?? "Training plan unavailable.")}</p>`; return; }
    const available = this.#state.exercises.filter((item) => !this.#draft.some((draft) => draft.exerciseId === item.id) && (!this.#exerciseQuery || norm(item.name).includes(norm(this.#exerciseQuery))));
    const rows = this.#draft.map((draft) => { const exercise = this.#exercise(draft.exerciseId); if (!exercise) return ""; const guidance = this.#guidanceFor(draft.exerciseId); const chosen = draft.variantIds.map((id) => { const variant = exercise.variants.find((candidate) => candidate.id === id); const override = guidance.overrides[id]; return `<li class="configurator-training-plan-variant"><span><strong>${esc(variant?.name ?? id)}</strong><small class="${override ? "configurator-training-plan-guidance--exception" : ""}">${override ? `Exception: ${esc(this.#guidanceSummary(override))}` : "Inherits exercise guidance"}</small></span><div class="configurator-training-plan-variant-actions"><button type="button" class="configurator-training-plan-guidance-action" data-ui-action="open-variant-guidance" data-exercise-id="${esc(draft.exerciseId)}" data-variant-id="${esc(id)}" aria-haspopup="dialog" aria-label="Edit guidance exception for ${esc(variant?.name ?? "Variant")}">${override ? "Edit exception" : "Add exception"}</button><button type="button" class="configurator-training-plan-remove" data-ui-action="remove-plan-variant" data-exercise-id="${esc(draft.exerciseId)}" data-variant-id="${esc(id)}" aria-label="Remove ${esc(variant?.name ?? "Variant")}"${draft.variantIds.length === 1 ? " disabled" : ""}><span aria-hidden="true">×</span></button></div></li>`; }).join(""); const hasAvailableVariant = exercise.variants.some((variant) => !draft.variantIds.includes(variant.id)); return `<section class="configurator-training-plan-exercise-card" data-exercise-id="${esc(draft.exerciseId)}"><div class="configurator-training-plan-exercise-heading"><h3>${draft.position}. ${esc(exercise.name)} <span class="configurator-training-plan-variant-count">${draft.variantIds.length}/${exercise.variants.length} variants</span></h3><button type="button" class="configurator-training-plan-remove" data-ui-action="remove-plan-exercise" data-exercise-id="${esc(draft.exerciseId)}" aria-label="Remove ${esc(exercise.name)}"><span aria-hidden="true">×</span></button></div><div class="configurator-training-plan-guidance"><small>Default guidance: ${esc(this.#guidanceSummary(guidance.defaults))}</small><button type="button" class="configurator-training-plan-guidance-action" data-ui-action="open-exercise-guidance" data-exercise-id="${esc(draft.exerciseId)}" aria-haspopup="dialog">Edit guidance</button></div><ul class="configurator-training-plan-variant-list">${chosen}</ul>${hasAvailableVariant ? `<button type="button" class="configurator-training-plan-add-action" data-ui-action="open-plan-variant-picker" data-exercise-id="${esc(draft.exerciseId)}" aria-haspopup="dialog" aria-expanded="${this.#variantPickerExerciseId === draft.exerciseId}">+ Add Variant</button>` : ""}</section>`; }).join("");
    const reorderRows = this.#draft.map((draft) => { const exercise = this.#exercise(draft.exerciseId); const moving = this.#dragging?.exerciseId === draft.exerciseId; const insertion = !moving && this.#insertionExerciseId === draft.exerciseId; const insertionAfter = !moving && this.#insertionAfterExerciseId === draft.exerciseId; return exercise ? `<li class="configurator-training-plan-reorder-row${moving ? " configurator-training-plan-reorder-row--moving" : ""}${insertion ? " configurator-training-plan-reorder-row--insertion" : ""}${insertionAfter ? " configurator-training-plan-reorder-row--insertion-after" : ""}" data-exercise-id="${esc(draft.exerciseId)}"><button type="button" class="configurator-training-plan-reorder-handle" data-reorder-handle data-exercise-id="${esc(draft.exerciseId)}" aria-label="Move ${esc(exercise.name)}" aria-pressed="${moving}">⠿</button><span class="configurator-training-plan-reorder-position">${draft.position}</span><span class="configurator-training-plan-reorder-name">${esc(exercise.name)}</span></li>` : ""; }).join("");
    const confirmation = this.#saveConfirmation ? `<div class="confirm-dialog-layer" role="presentation"><div class="confirm-dialog-backdrop" role="presentation"></div><section class="confirm-dialog" role="alertdialog" aria-modal="true" aria-label="Save training plan changes"><p class="confirm-dialog-message">${esc(this.#saveConfirmation)}</p><div class="confirm-dialog-actions"><button type="button" class="nav-button nav-button-secondary" data-ui-action="dismiss-training-plan-save-confirmation">Keep Editing</button><button type="button" class="nav-button" data-ui-action="confirm-training-plan-save">Save Changes</button></div></section></div>` : "";
    const editor = this.#reordering
      ? `<section class="configurator-training-plan-reorder" aria-label="Reorder exercises"><header class="configurator-training-plan-section-header"><h2>Reorder Exercises · ${this.#draft.length}</h2></header><ol class="configurator-training-plan-reorder-list">${reorderRows}</ol><button type="button" class="configurator-gym-save-button" data-ui-action="finish-plan-exercise-reorder">Done</button></section>`
      : `<form class="configurator-training-plan-editor-card" onsubmit="return false"><label class="configurator-gym-field"><span class="configurator-gym-field-label">Plan name</span><input class="configurator-gym-input" data-field="plan-name" value="${esc(this.#name)}" /></label><div class="configurator-training-plan-section-header"><h2>Exercises · ${this.#draft.length}</h2><button type="button" class="configurator-training-plan-reorder-action" data-ui-action="start-plan-exercise-reorder">Reorder</button></div>${rows}<button type="button" class="configurator-training-plan-add-action" data-ui-action="open-plan-exercise-picker" aria-haspopup="dialog" aria-expanded="${this.#exercisePickerOpen}">+ Add Exercise</button>${this.#error ? `<p class="start-error" role="alert">${esc(this.#error)}</p>` : ""}<button type="button" class="configurator-gym-save-button" data-ui-action="save-configurator-training-plan"${this.#saving || this.#assessingSave ? " disabled" : ""}>${this.#saving ? "Saving..." : this.#assessingSave ? "Checking changes..." : "Save Training Plan"}</button></form>`;
    this.innerHTML = `<div class="app-screen-shell"><button type="button" class="side-menu-toggle detail-back-button" data-ui-action="navigate-back-from-configurator-training-plan-detail" aria-label="Back to Training Plans"><span aria-hidden="true">←</span></button><section class="screen-panel configurator-training-plan-editor-screen" aria-label="Edit current training plan"><header class="app-header configurator-app-header"><h1 class="app-title">${esc(detail.name)}</h1><p class="start-copy">Current plan definition</p></header>${editor}</section>${this.#renderExercisePicker(available)}${this.#renderVariantPicker()}${this.#renderGuidanceOverlay()}${confirmation}</div>`;
  }
}
export const registerPbConfiguratorTrainingPlanEditorScreen = (): void => { if (!customElements.get(pbConfiguratorTrainingPlanEditorScreenTag)) customElements.define(pbConfiguratorTrainingPlanEditorScreenTag, PbConfiguratorTrainingPlanEditorScreenElement); };
