import type { ConfiguratorExerciseVariant, ConfiguratorExerciseVariantCompatibilityResponse, ConfiguratorExerciseVariantCreateRequest, ConfiguratorExerciseVariantUpdateRequest } from "./workout-contract";
import { TextInputBinding } from "./text-input-binding";
import { ModalFocus } from "./modal-focus";
import { formatConfiguratorLifecycleStatus } from "./pb-configurator-status";
import "./pb-configurator-header";
import "./pb-confirm-dialog";
export const pbConfiguratorExerciseVariantEditorScreenTag = "pb-configurator-exercise-variant-editor-screen";
export type ConfiguratorExerciseVariantEditorScreenState = { exerciseId: string; exerciseName: string; variant: ConfiguratorExerciseVariant | null; isLoading: boolean; errorMessage: string | null; compatibility?: ConfiguratorExerciseVariantCompatibilityResponse | null; isCompatibilityLoading?: boolean; compatibilityError?: string | null };
type Result = { ok: boolean; errorMessage?: string };
const esc = (v: string) => v.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#39;");
class PbConfiguratorExerciseVariantEditorScreenElement extends HTMLElement {
  #state: ConfiguratorExerciseVariantEditorScreenState = { exerciseId: "", exerciseName: "", variant: null, isLoading: false, errorMessage: null }; #key: string | null = null;
  #name = ""; #requires = true; #load: "TOTAL" | "PER_SIDE" = "TOTAL"; #tracking: "BILATERAL" | "UNILATERAL" = "BILATERAL"; #reps: "REPS" | "SECS" = "REPS"; #saving = false; #deleting = false; #warning = false; #error: string | null = null; #touched = false;
  #picker = false; #search = ""; #selected = new Set<string>(); #compatSaving = false; #compatError: string | null = null;
  #modalFocus = new ModalFocus(this);
  #text = new TextInputBinding(this, ({ field, value }) => this.#input(field, value));
  connectedCallback() { this.#render(); this.addEventListener("click", this.#click); this.addEventListener("change", this.#change); this.addEventListener("keydown", this.#keyDown); this.#text.connect(); }
  disconnectedCallback() { this.removeEventListener("click", this.#click); this.removeEventListener("change", this.#change); this.removeEventListener("keydown", this.#keyDown); this.#text.disconnect(); }
  set state(v: ConfiguratorExerciseVariantEditorScreenState) { this.#state = v; const key = v.variant ? `edit:${v.variant.id}` : `create:${v.exerciseId}`; if (key !== this.#key) { this.#key = key; const x = v.variant; this.#name = x?.name ?? ""; this.#requires = x?.requires_station ?? true; this.#load = x?.load_input_mode ?? "TOTAL"; this.#tracking = x?.set_tracking_mode ?? "BILATERAL"; this.#reps = x?.repetition_kind ?? "REPS"; this.#saving = false; this.#deleting = false; this.#warning = false; this.#error = null; this.#touched = false; this.#picker = false; this.#search = ""; this.#selected = new Set(); this.#compatSaving = false; this.#compatError = null; } this.#render(); }
  get state() { return this.#state; }
  #historical = () => this.#state.variant?.status === "active" || this.#state.variant?.status === "inactive";
  #hasChanges = () => {
    const variant = this.#state.variant;
    const fieldsChanged = !variant
      ? this.#name.trim().length > 0 || !this.#requires || this.#load !== "TOTAL" || this.#tracking !== "BILATERAL" || this.#reps !== "REPS"
      : this.#name.trim() !== variant.name.trim() || (!this.#historical() && (
        this.#requires !== variant.requires_station || this.#load !== variant.load_input_mode || this.#tracking !== variant.set_tracking_mode || this.#reps !== variant.repetition_kind
      ));
    const enabled = new Set((this.#state.compatibility?.enabled_stations ?? []).map((station) => station.station_id));
    const compatibilityChanged = this.#picker && (enabled.size !== this.#selected.size || [...enabled].some((stationId) => !this.#selected.has(stationId)));
    return fieldsChanged || compatibilityChanged;
  };
  #emitDraftState = () => this.#emit("configurator-draft-state-changed", { source: "configurator-exercise-variant-detail", isDirty: this.#hasChanges() });
  #emit(action: string, payload?: object) { this.dispatchEvent(new CustomEvent("pb-ui-action", { bubbles: true, composed: true, detail: { action, ...(payload ? { payload } : {}) } })); }
  #input(field: string, value: string) { if (field === "compatibility-search") { this.#search = value; this.#render(); } else if (field === "name") { this.#name = value; this.#touched = true; this.#error = null; this.#emitDraftState(); this.querySelector(".configurator-field-error, .start-error")?.remove(); const input = this.querySelector<HTMLInputElement>('[data-field="name"]'); if (input) { const invalid = !this.#name.trim(); input.setAttribute("aria-invalid", `${invalid}`); if (invalid) input.setAttribute("aria-describedby", "configurator-exercise-variant-name-error"); else input.removeAttribute("aria-describedby"); } if (!this.#name.trim()) { const fieldElement = input?.closest(".configurator-field"); if (fieldElement) { const message = document.createElement("span"); message.id = "configurator-exercise-variant-name-error"; message.className = "configurator-field-error"; message.textContent = "Name is required."; fieldElement.append(message); } } const button = this.querySelector<HTMLButtonElement>('[data-ui-action="save-configurator-exercise-variant"]'); if (button) button.disabled = this.#saving || this.#deleting || !this.#name.trim(); } }
  #change = (e: Event) => { if (this.#historical() || !(e.target instanceof HTMLInputElement)) return; const t = e.target; if (t.dataset.field === "requires-station") this.#requires = t.checked; if (t.dataset.field === "load-input-mode" && (t.value === "TOTAL" || t.value === "PER_SIDE")) this.#load = t.value; if (t.dataset.field === "set-tracking-mode" && (t.value === "BILATERAL" || t.value === "UNILATERAL")) this.#tracking = t.value; if (t.dataset.field === "repetition-kind" && (t.value === "REPS" || t.value === "SECS")) this.#reps = t.value; this.#touched = true; this.#emitDraftState(); this.#render(); };
  #keyDown = (e: KeyboardEvent) => { this.#modalFocus.handleKeyDown(e, this.querySelector<HTMLElement>("[role=dialog]"), () => this.#dismissPicker()); };
  #openPicker(invoker: HTMLElement) { this.#selected = new Set((this.#state.compatibility?.enabled_stations ?? []).map(x => x.station_id)); this.#search = ""; this.#compatError = null; this.#picker = true; this.#render(); this.#modalFocus.open(invoker, '[data-field="compatibility-search"]'); }
  #dismissPicker() { this.#picker = false; this.#search = ""; this.#compatError = null; this.#compatSaving = false; this.#render(); this.#modalFocus.close(); }
  #toggle(stationId: string) { if (this.#compatSaving || !(this.#state.compatibility?.eligible_stations ?? []).some(x => x.station_id === stationId)) return; const scrollTop = this.querySelector<HTMLElement>(".configurator-exercise-variant-compatibility-picker-options")?.scrollTop ?? 0; if (this.#selected.has(stationId)) this.#selected.delete(stationId); else this.#selected.add(stationId); this.#compatError = null; this.#emitDraftState(); this.#render(); const options = this.querySelector<HTMLElement>(".configurator-exercise-variant-compatibility-picker-options"); if (options) options.scrollTop = scrollTop; }
  #click = (e: Event) => { const target = e.target instanceof Element ? e.target : null; const action = target?.closest<HTMLElement>("[data-ui-action]")?.dataset.uiAction; if (!action) return;
    if (action === "navigate-back-from-configurator-exercise-variant-detail") return this.#emit(action);
    if (action === "open-configurator-exercise-variant-compatibility-picker") return this.#openPicker(target!.closest<HTMLElement>("[data-ui-action]")!);
    if (action === "dismiss-configurator-exercise-variant-compatibility-picker") return this.#dismissPicker();
    if (action === "open-configurator-exercise-variant-compatible-station") { const row = target!.closest<HTMLElement>("[data-gym-id][data-station-id]"); const gymId = row?.dataset.gymId, stationId = row?.dataset.stationId; if (gymId && stationId) this.#emit(action, { gymId, stationId }); return; }
    if (action === "toggle-configurator-exercise-variant-compatibility") { const id = target!.closest<HTMLElement>("[data-station-id]")?.dataset.stationId; if (id) this.#toggle(id); return; }
    if (action === "save-configurator-exercise-variant-compatibilities") { const variantId = this.#state.variant?.id; if (!variantId || this.#compatSaving) return; this.#compatSaving = true; this.#compatError = null; this.#render(); this.dispatchEvent(new CustomEvent("pb-ui-action", { bubbles: true, composed: true, detail: { action, payload: { exerciseId: this.#state.exerciseId, variantId, stationIds: [...this.#selected] }, respond: (r: Result) => { this.#compatSaving = false; if (r.ok) this.#dismissPicker(); else { this.#compatError = r.errorMessage ?? "Unable to save compatible Stations right now."; this.#render(); } } } })); return; }
    if (action === "dismiss-historical-variant-rename-warning") { this.#warning = false; this.#render(); return; }
    if (action === "save-configurator-exercise-variant") { if (!this.#name.trim()) { this.#touched = true; this.#error = "Name is required."; this.#render(); return; } if (this.#historical() && this.#name.trim() !== this.#state.variant?.name && !this.#warning) { this.#warning = true; this.#render(); return; } if (this.#saving || this.#deleting) return; const request = this.#state.variant && this.#historical() ? { name: this.#name.trim() } : { name: this.#name.trim(), requires_station: this.#requires, load_input_mode: this.#load, set_tracking_mode: this.#tracking, repetition_kind: this.#reps }; this.#saving = true; this.#warning = false; this.#render(); this.dispatchEvent(new CustomEvent("pb-ui-action", { bubbles: true, composed: true, detail: { action, payload: { exerciseId: this.#state.exerciseId, variantId: this.#state.variant?.id ?? null, request: request as ConfiguratorExerciseVariantCreateRequest | ConfiguratorExerciseVariantUpdateRequest }, respond: (r: Result) => { this.#saving = false; this.#error = r.ok ? null : r.errorMessage ?? null; this.#render(); } } })); return; }
    if (action === "delete-configurator-exercise-variant") { const v = this.#state.variant; if (!v || v.status !== "new" || this.#saving || this.#deleting) return; this.#deleting = true; this.#render(); this.dispatchEvent(new CustomEvent("pb-ui-action", { bubbles: true, composed: true, detail: { action, payload: { exerciseId: this.#state.exerciseId, variantId: v.id }, respond: (r: Result) => { this.#deleting = false; this.#error = r.ok ? null : r.errorMessage ?? null; this.#render(); } } })); }
  };
  #compatibility() { const v = this.#state.variant; if (!v?.requires_station) return ""; if (this.#state.isCompatibilityLoading) return '<section class="configurator-exercise-variant-compatibility"><h2>Compatible Stations</h2><p class="start-copy" role="status">Loading compatible Stations…</p></section>'; if (this.#state.compatibilityError) return `<section class="configurator-exercise-variant-compatibility"><h2>Compatible Stations</h2><p class="start-error" role="alert">${esc(this.#state.compatibilityError)}</p></section>`; const stations = this.#state.compatibility?.enabled_stations ?? []; const groups = new Map<string, typeof stations>(); stations.forEach(x => groups.set(`${x.gym_id}:${x.gym_name}`, [...(groups.get(`${x.gym_id}:${x.gym_name}`) ?? []), x])); const rows = [...groups.values()].map(g => `<li><h3>${esc(g[0].gym_name)}</h3><ul>${g.map(x => `<li><button type="button" class="configurator-exercise-variant-station-row" data-ui-action="open-configurator-exercise-variant-compatible-station" data-gym-id="${esc(x.gym_id)}" data-station-id="${esc(x.station_id)}">${esc(x.station_name)}</button></li>`).join("")}</ul></li>`).join(""); return `<section class="configurator-exercise-variant-compatibility"><div class="configurator-exercise-variant-compatibility-header"><div><h2>Compatible Stations</h2><p>${stations.length} enabled</p></div><button type="button" class="configurator-action-secondary configurator-exercise-variant-compatibility-edit" data-ui-action="open-configurator-exercise-variant-compatibility-picker">Edit</button></div>${rows ? `<ul class="configurator-exercise-variant-station-groups">${rows}</ul>` : ""}</section>`; }
  #pickerMarkup() { if (!this.#picker) return ""; const all = this.#state.compatibility?.eligible_stations ?? []; const q = this.#search.trim().toLocaleLowerCase("en-US"); const matches = all.filter(x => `${x.station_name} ${x.gym_name}`.toLocaleLowerCase("en-US").includes(q)); const groups = new Map<string, typeof matches>(); matches.forEach(x => groups.set(`${x.gym_id}:${x.gym_name}`, [...(groups.get(`${x.gym_id}:${x.gym_name}`) ?? []), x])); const options = [...groups.values()].map(g => `<section class="configurator-exercise-variant-compatibility-picker-gym"><h3 class="configurator-exercise-variant-compatibility-picker-gym-heading">${esc(g[0].gym_name)}</h3>${g.map(x => `<button type="button" class="configurator-exercise-variant-compatibility-picker-option${this.#selected.has(x.station_id) ? " configurator-exercise-variant-compatibility-picker-option--selected" : ""}" data-ui-action="toggle-configurator-exercise-variant-compatibility" data-station-id="${esc(x.station_id)}" role="checkbox" aria-checked="${this.#selected.has(x.station_id)}"><span>${esc(x.station_name)}</span><span aria-hidden="true">${this.#selected.has(x.station_id) ? "✓" : ""}</span></button>`).join("")}</section>`).join(""); return `<div class="secs-picker-layer"><button type="button" class="secs-picker-backdrop" data-ui-action="dismiss-configurator-exercise-variant-compatibility-picker" aria-label="Cancel compatible Station selection"></button><section class="secs-picker-sheet configurator-exercise-variant-compatibility-picker" role="dialog" aria-modal="true" aria-labelledby="configurator-exercise-variant-compatibility-picker-title"><header class="configurator-load-profile-picker-header"><div><h2 id="configurator-exercise-variant-compatibility-picker-title" class="secs-picker-title">Compatible Stations</h2><p class="configurator-exercise-variant-compatibility-picker-count">${this.#selected.size} selected</p></div><input class="configurator-control" data-field="compatibility-search" type="search" value="${esc(this.#search)}" placeholder="Search Stations or Gyms" aria-label="Search Stations or Gyms" /></header><div class="configurator-exercise-variant-compatibility-picker-options">${options || '<p class="start-copy">No matching Stations.</p>'}</div>${this.#compatError ? `<p class="start-error">${esc(this.#compatError)}</p>` : ""}<div class="configurator-exercise-variant-compatibility-picker-actions"><button type="button" class="configurator-action-dismiss" data-ui-action="dismiss-configurator-exercise-variant-compatibility-picker">Cancel</button><button type="button" class="configurator-action-primary" data-ui-action="save-configurator-exercise-variant-compatibilities">${this.#compatSaving ? "Saving..." : "Save"}</button></div></section></div>`; }
  #render() {
    const v = this.#state.variant, historical = this.#historical(), disabled = this.#saving || this.#deleting || !this.#name.trim();
    const field = (l: string, b: string, id: string) => `<label class="configurator-field" for="${id}"><span class="configurator-field-label">${l}</span>${b}</label>`;
    const choice = (l: string, n: string, val: string, yes: boolean) => `<label class="configurator-option-choice"><input id="configurator-exercise-variant-${n}-${val.toLocaleLowerCase().replaceAll("_", "-")}" type="radio" data-field="${n}" name="${n}" value="${val}" aria-required="false" aria-invalid="false" ${yes ? "checked" : ""}/> ${l}</label>`;
    const optionGroup = (l: string, choices: string) => `<fieldset class="configurator-field configurator-option-group" aria-required="false"><legend class="configurator-field-label">${l}</legend><div class="configurator-option-choices">${choices}</div></fieldset>`;
    const structural = historical
      ? `<dl class="configurator-metadata"><div><dt>Requires station</dt><dd>${this.#requires ? "Yes" : "No"}</dd></div></dl>`
      : `${field("Requires station", `<input id="configurator-exercise-variant-requires-station" type="checkbox" data-field="requires-station" aria-required="false" aria-invalid="false" ${this.#requires ? "checked" : ""}/>`, "configurator-exercise-variant-requires-station")}${optionGroup("Load input", choice("Total", "load-input-mode", "TOTAL", this.#load === "TOTAL") + choice("Per side", "load-input-mode", "PER_SIDE", this.#load === "PER_SIDE"))}${optionGroup("Set tracking", choice("Bilateral", "set-tracking-mode", "BILATERAL", this.#tracking === "BILATERAL") + choice("Unilateral", "set-tracking-mode", "UNILATERAL", this.#tracking === "UNILATERAL"))}${optionGroup("Repetition kind", choice("Reps", "repetition-kind", "REPS", this.#reps === "REPS") + choice("Seconds", "repetition-kind", "SECS", this.#reps === "SECS"))}`;
    const body = this.#state.isLoading ? '<p class="start-status">Loading Variant...</p>' : this.#state.errorMessage ? `<p class="start-error">${esc(this.#state.errorMessage)}</p>` : `<div class="configurator-editor-card">${field("Name", `<input id="configurator-exercise-variant-name" class="configurator-control" data-field="name" value="${esc(this.#name)}" required aria-required="true" aria-invalid="${!this.#name.trim() ? "true" : "false"}"${this.#touched && !this.#name.trim() ? ' aria-describedby="configurator-exercise-variant-name-error"' : ""}/>${this.#touched && !this.#name.trim() ? '<span id="configurator-exercise-variant-name-error" class="configurator-field-error">Name is required.</span>' : ""}`, "configurator-exercise-variant-name")}${v ? `<dl class="configurator-metadata"><div><dt>Status</dt><dd>${formatConfiguratorLifecycleStatus(v.status)}</dd></div></dl>` : ""}${structural}${this.#compatibility()}${this.#error ? `<p class="start-error">${esc(this.#error)}</p>` : ""}<div class="configurator-editor-actions"><button type="button" class="configurator-action-primary" data-ui-action="save-configurator-exercise-variant" ${disabled ? "disabled" : ""}>${this.#saving ? "Saving..." : v ? "Save Variant" : "Create Variant"}</button>${v?.status === "new" ? `<button type="button" class="configurator-action-danger" data-ui-action="delete-configurator-exercise-variant">${this.#deleting ? "Deleting..." : "Delete Draft"}</button>` : ""}</div></div>`;
    const warning = this.#warning ? "<pb-confirm-dialog></pb-confirm-dialog>" : "";
    this.innerHTML = `<div class="app-screen-shell"><button type="button" class="side-menu-toggle detail-back-button" data-ui-action="navigate-back-from-configurator-exercise-variant-detail" aria-label="Back">←</button><section class="screen-panel configurator-gym-editor-screen" aria-label="Variant editor"><pb-configurator-header title="${v ? "Variant" : "New Variant"}" context="${esc(this.#state.exerciseName)}" banner></pb-configurator-header>${body}</section>${warning}${this.#pickerMarkup()}</div>`;
    const dialog = this.querySelector<HTMLElement>("pb-confirm-dialog") as HTMLElement & { state: import("./pb-confirm-dialog").ConfirmDialogState } | null;
    if (dialog) dialog.state = { accessibleName: "Historical variant rename warning", message: "Renaming an active or inactive Variant can affect how historical workouts are understood. Save this name change?", dismissAction: "dismiss-historical-variant-rename-warning", dismissLabel: "Keep Editing", confirmAction: "save-configurator-exercise-variant", confirmLabel: "Save Name", backdrop: false };
  }
}
export const registerPbConfiguratorExerciseVariantEditorScreen = () => { if (typeof customElements !== "undefined" && !customElements.get(pbConfiguratorExerciseVariantEditorScreenTag)) customElements.define(pbConfiguratorExerciseVariantEditorScreenTag, PbConfiguratorExerciseVariantEditorScreenElement); };
registerPbConfiguratorExerciseVariantEditorScreen();
