import type { ConfiguratorExerciseVariant, ExerciseSummary, TrainingPlanDefinitionRequest, TrainingPlanDetailResponse } from "./workout-contract";
import { TextInputBinding } from "./text-input-binding";

export const pbConfiguratorTrainingPlanEditorScreenTag = "pb-configurator-training-plan-editor-screen";
type ExerciseOption = ExerciseSummary & { variants: ConfiguratorExerciseVariant[] };
export type ConfiguratorTrainingPlanEditorScreenState = { trainingPlanId: string; detail: TrainingPlanDetailResponse | null; exercises: ExerciseOption[]; isLoading: boolean; errorMessage: string | null };
type DraftExercise = { exerciseId: string; variantIds: string[]; position: number; original: boolean };
type SaveResult = { ok: boolean; errorMessage?: string };
const esc = (v: string) => v.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#39;");
const norm = (v: string) => v.trim().toLocaleLowerCase("en-US");

class PbConfiguratorTrainingPlanEditorScreenElement extends HTMLElement {
  #state: ConfiguratorTrainingPlanEditorScreenState = { trainingPlanId: "", detail: null, exercises: [], isLoading: false, errorMessage: null };
  #loaded = ""; #name = ""; #draft: DraftExercise[] = []; #exerciseQuery = ""; #variantQuery = new Map<string, string>(); #error: string | null = null; #saving = false;
  #textInput = new TextInputBinding(this, ({ field, value }) => this.#onTextInput(field, value));
  connectedCallback(): void { this.#render(); this.addEventListener("click", this.#onClick); this.#textInput.connect(); }
  disconnectedCallback(): void { this.removeEventListener("click", this.#onClick); this.#textInput.disconnect(); }
  set state(value: ConfiguratorTrainingPlanEditorScreenState) { this.#state = value; const key = value.detail ? `${value.trainingPlanId}:${value.detail.selected_version_number}` : ""; if (key && key !== this.#loaded) { this.#loaded = key; this.#name = value.detail!.name; this.#draft = value.detail!.exercises.map((item) => ({ exerciseId: this.#exerciseFor(item.variants[0]?.variant_id ?? ""), variantIds: item.variants.map((variant) => variant.variant_id), position: item.exercise_position, original: true })).filter((item) => item.exerciseId); this.#error = null; this.#saving = false; } this.#render(); }
  get state(): ConfiguratorTrainingPlanEditorScreenState { return this.#state; }
  #exerciseFor(variantId: string): string { return this.#state.exercises.find((exercise) => exercise.variants.some((variant) => variant.id === variantId))?.id ?? ""; }
  #exercise(id: string) { return this.#state.exercises.find((item) => item.id === id) ?? null; }
  #emit(action: string, payload?: Record<string, unknown>, respond?: (result: SaveResult) => void) { this.dispatchEvent(new CustomEvent("pb-ui-action", { bubbles: true, composed: true, detail: { action, ...(payload ? { payload } : {}), ...(respond ? { respond } : {}) } })); }
  #onTextInput(field: string, value: string): void { if (field === "plan-name") this.#name = value; else if (field === "exercise-search") this.#exerciseQuery = value; else if (field.startsWith("variant-search:")) this.#variantQuery.set(field.slice("variant-search:".length), value); else return; this.#error = null; this.#render(); }
  #onClick = (event: Event) => { const target = event.target; if (!(target instanceof Element)) return; const button = target.closest<HTMLElement>("[data-ui-action]"); if (!button || !this.contains(button)) return; const action = button.dataset.uiAction;
    if (action === "navigate-back-from-configurator-training-plan-detail") return this.#emit(action);
    if (action === "add-plan-exercise") { const id = button.dataset.exerciseId ?? ""; if (this.#exercise(id) && !this.#draft.some((item) => item.exerciseId === id)) { this.#draft.push({ exerciseId: id, variantIds: [], position: this.#draft.length + 1, original: false }); this.#exerciseQuery = ""; this.#render(); } return; }
    if (action === "remove-plan-exercise") { const id = button.dataset.exerciseId ?? ""; this.#draft = this.#draft.filter((item) => item.exerciseId !== id); this.#render(); return; }
    if (action === "add-plan-variant") { const exerciseId = button.dataset.exerciseId ?? "", variantId = button.dataset.variantId ?? ""; const item = this.#draft.find((candidate) => candidate.exerciseId === exerciseId); if (item && !item.variantIds.includes(variantId)) { item.variantIds.push(variantId); this.#variantQuery.set(exerciseId, ""); this.#render(); } return; }
    if (action === "remove-plan-variant") { const exerciseId = button.dataset.exerciseId ?? "", variantId = button.dataset.variantId ?? ""; const item = this.#draft.find((candidate) => candidate.exerciseId === exerciseId); if (item && item.variantIds.length > 1) { item.variantIds = item.variantIds.filter((id) => id !== variantId); this.#render(); } return; }
    if (action !== "save-configurator-training-plan" || this.#saving) return;
    if (!this.#name.trim() || this.#draft.length === 0 || this.#draft.some((item) => item.variantIds.length === 0)) { this.#error = !this.#name.trim() ? "Plan name is required." : this.#draft.length === 0 ? "Add at least one Exercise." : "Choose at least one Variant for every Exercise."; this.#render(); return; }
    const request: TrainingPlanDefinitionRequest = { name: this.#name.trim(), exercises: this.#draft.map((item) => ({ exercise_id: item.exerciseId, allowed_variant_ids: item.variantIds })) };
    const original = this.#state.detail!; const renamed = norm(original.name) !== norm(request.name); const originalExercises = original.exercises.map((item) => this.#exerciseFor(item.variants[0]?.variant_id ?? "")); const structural = originalExercises.length !== this.#draft.length || originalExercises.some((id, index) => id !== this.#draft[index]?.exerciseId) || original.exercises.some((item) => item.variants.some((variant) => !this.#draft.find((draft) => draft.exerciseId === this.#exerciseFor(item.variants[0]?.variant_id ?? ""))?.variantIds.includes(variant.variant_id)));
    const save = () => { this.#saving = true; this.#render(); this.#emit("save-configurator-training-plan", { trainingPlanId: this.#state.trainingPlanId, request }, (result) => { this.#saving = false; this.#error = result.ok ? null : result.errorMessage ?? "Unable to save training plan right now."; this.#render(); }); };
    if (renamed || structural) { const parts = [renamed ? "The plan name will be updated." : "", structural ? "These structural changes may create a new plan version." : ""].filter(Boolean); this.#emit("confirm-configurator-training-plan-save", { message: parts.join(" ") }, () => save()); } else save();
  };
  #guidance(variant: { target_sets: number | null; rep_min: number | null; rep_max: number | null }): string { const sets = variant.target_sets === null ? "Sets not set" : `${variant.target_sets} sets`; const reps = variant.rep_min === null || variant.rep_max === null ? "reps not set" : variant.rep_min === variant.rep_max ? `${variant.rep_min} reps` : `${variant.rep_min}–${variant.rep_max} reps`; return `${sets} · ${reps}`; }
  #render(): void { const detail = this.#state.detail; if (this.#state.isLoading) { this.innerHTML = '<p class="start-status">Loading training plan...</p>'; return; } if (this.#state.errorMessage || !detail) { this.innerHTML = `<p class="start-error" role="alert">${esc(this.#state.errorMessage ?? "Training plan unavailable.")}</p>`; return; }
    const available = this.#state.exercises.filter((item) => !this.#draft.some((draft) => draft.exerciseId === item.id) && (!this.#exerciseQuery || norm(item.name).includes(norm(this.#exerciseQuery))));
    const rows = this.#draft.map((draft) => { const exercise = this.#exercise(draft.exerciseId); if (!exercise) return ""; const query = this.#variantQuery.get(draft.exerciseId) ?? ""; const choices = exercise.variants.filter((variant) => !draft.variantIds.includes(variant.id) && (!query || norm(variant.name).includes(norm(query)))); const chosen = draft.variantIds.map((id) => { const variant = exercise.variants.find((candidate) => candidate.id === id); const info = detail.exercises.flatMap((item) => item.variants).find((candidate) => candidate.variant_id === id); return `<li class="configurator-training-plan-variant"><span>${esc(variant?.name ?? id)}${info ? `<small>${esc(this.#guidance(info))}</small>` : ""}</span><button type="button" class="nav-button nav-button-secondary" data-ui-action="remove-plan-variant" data-exercise-id="${esc(draft.exerciseId)}" data-variant-id="${esc(id)}"${draft.variantIds.length === 1 ? " disabled" : ""}>Remove</button></li>`; }).join(""); return `<section class="configurator-training-plan-exercise-card" data-exercise-id="${esc(draft.exerciseId)}"><div class="configurator-training-plan-exercise-heading"><h3>${draft.position}. ${esc(exercise.name)}</h3><button type="button" class="nav-button nav-button-secondary" data-ui-action="remove-plan-exercise" data-exercise-id="${esc(draft.exerciseId)}">Remove Exercise</button></div><h4>Allowed Variants</h4><ul class="configurator-training-plan-variant-list">${chosen}</ul><label class="configurator-gym-field"><span class="configurator-gym-field-label">Find Variant</span><input class="configurator-gym-input" type="search" data-field="variant-search:${esc(draft.exerciseId)}" value="${esc(query)}" /></label><div class="configurator-training-plan-option-actions">${choices.map((variant) => `<button type="button" class="nav-button nav-button-secondary" data-ui-action="add-plan-variant" data-exercise-id="${esc(draft.exerciseId)}" data-variant-id="${esc(variant.id)}">Add ${esc(variant.name)}</button>`).join("") || ""}</div></section>`; }).join("");
    this.innerHTML = `<div class="app-screen-shell"><button type="button" class="side-menu-toggle detail-back-button" data-ui-action="navigate-back-from-configurator-training-plan-detail" aria-label="Back to Training Plans"><span aria-hidden="true">←</span></button><section class="screen-panel configurator-training-plan-editor-screen" aria-label="Edit current training plan"><header class="app-header configurator-app-header"><h1 class="app-title">${esc(detail.name)}</h1><p class="start-copy">Current plan definition</p></header><form class="configurator-training-plan-editor-card" onsubmit="return false"><label class="configurator-gym-field"><span class="configurator-gym-field-label">Plan name</span><input class="configurator-gym-input" data-field="plan-name" value="${esc(this.#name)}" /></label>${rows}<section class="configurator-training-plan-exercise-card"><h3>Add Exercise</h3><label class="configurator-gym-field"><span class="configurator-gym-field-label">Find Exercise</span><input class="configurator-gym-input" type="search" data-field="exercise-search" value="${esc(this.#exerciseQuery)}" /></label><div class="configurator-training-plan-option-actions">${available.map((exercise) => `<button type="button" class="nav-button nav-button-secondary" data-ui-action="add-plan-exercise" data-exercise-id="${esc(exercise.id)}">Add ${esc(exercise.name)}</button>`).join("")}</div></section>${this.#error ? `<p class="start-error" role="alert">${esc(this.#error)}</p>` : ""}<button type="button" class="configurator-gym-save-button" data-ui-action="save-configurator-training-plan"${this.#saving ? " disabled" : ""}>${this.#saving ? "Saving..." : "Save Training Plan"}</button></form></section></div>`;
  }
}
export const registerPbConfiguratorTrainingPlanEditorScreen = (): void => { if (!customElements.get(pbConfiguratorTrainingPlanEditorScreenTag)) customElements.define(pbConfiguratorTrainingPlanEditorScreenTag, PbConfiguratorTrainingPlanEditorScreenElement); };
